const entries = [
    {
        title: "Blade",
        type: "Movie",
        universe: ["Miscellaneous"],
        phase: [],
        saga: [],
        franchise: ["Blade"],
        medium: ["Live Action"],
        year: "1998",
        ranking: 60,
        tier: "good",
        poster: "imgs/posters/mcu/blade.jpg"
    },
    {
        title: "X-Men",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["X-Men (Originals)"],
        medium: ["Live Action"],
        year: "2000",
        ranking: 38,
        tier: "excellent",
        poster: "imgs/posters/mcu/xmen.jpg"
    },
    {
        title: "Blade II",
        type: "Movie",
        universe: ["Miscellaneous"],
        phase: [],
        saga: [],
        franchise: ["Blade"],
        medium: ["Live Action"],
        year: "2002",
        ranking: 67,
        tier: "good",
        poster: "imgs/posters/mcu/blade ii.jpg"
    },
    {
        title: "Spider-Man",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: ["Spider-Man (Tobey Maguire)"],
        medium: ["Live Action"],
        year: "2002",
        ranking: 28,
        tier: "best",
        poster: "imgs/posters/mcu/spiderman.jpg"
    },
    {
        title: "Daredevil",
        type: "Movie",
        universe: ["Miscellaneous"],
        phase: [],
        saga: [],
        franchise: ["Daredevil (Ben Affleck)"],
        medium: ["Live Action"],
        year: "2003",
        ranking: 104,
        tier: "mistake",
        poster: "imgs/posters/mcu/daredevil.jpg"
    },
    {
        title: "X2",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["X-Men (Originals)"],
        medium: ["Live Action"],
        year: "2003",
        ranking: 29,
        tier: "best",
        poster: "imgs/posters/mcu/x2.jpg"
    },
    {
        title: "Spider-Man 2",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: ["Spider-Man (Tobey Maguire)"],
        medium: ["Live Action"],
        year: "2004",
        ranking: 25,
        tier: "best",
        poster: "imgs/posters/mcu/spiderman 2.jpg"
    },
    {
        title: "Blade: Trinity",
        type: "Movie",
        universe: ["Miscellaneous"],
        phase: [],
        saga: [],
        franchise: ["Blade"],
        medium: ["Live Action"],
        year: "2004",
        ranking: 101,
        tier: "mistake",
        poster: "imgs/posters/mcu/blade trinity.jpg"
    },
    {
        title: "Elektra",
        type: "Movie",
        universe: ["Miscellaneous"],
        phase: [],
        saga: [],
        franchise: ["Daredevil (Ben Affleck)"],
        medium: ["Live Action"],
        year: "2005",
        ranking: 107,
        tier: "mistake",
        poster: "imgs/posters/mcu/elektra.jpg"
    },
    {
        title: "Fantastic Four (2005)",
        type: "Movie",
        universe: ["Miscellaneous"],
        phase: [],
        saga: [],
        franchise: ["Fantastic Four (2005)"],
        medium: ["Live Action"],
        year: "2005",
        ranking: 65,
        tier: "good",
        poster: "imgs/posters/mcu/fantastic four 2005.jpg"
    },
    {
        title: "X-Men: The Last Stand",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["X-Men (Originals)"],
        medium: ["Live Action"],
        year: "2006",
        ranking: 83,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/xmen the last stand.jpg"
    },
    {
        title: "Spider-Man 3",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: ["Spider-Man (Tobey Maguire)"],
        medium: ["Live Action"],
        year: "2006",
        ranking: 68,
        tier: "good",
        poster: "imgs/posters/mcu/spiderman 3.jpg"
    },
    {
        title: "Fantastic Four: Rise of the Silver Surfer",
        type: "Movie",
        universe: ["Miscellaneous"],
        phase: [],
        saga: [],
        franchise: ["Fantastic Four (2005)"],
        medium: ["Live Action"],
        year: "2007",
        ranking: 80,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/fantastic four rise of the silver surfer.jpg"
    },
    {
        title: "Iron Man",
        type: "Movie",
        universe: ["MCU"],
        phase: ["1"],
        saga: ["Infinity"],
        franchise: ["Iron Man"],
        medium: ["Live Action"],
        year: "2008",
        ranking: 33,
        tier: "excellent",
        poster: "imgs/posters/mcu/iron man.jpg"
    },
    {
        title: "The Incredible Hulk",
        type: "Movie",
        universe: ["MCU"],
        phase: ["1"],
        saga: ["Infinity"],
        franchise: [],
        medium: ["Live Action"],
        year: "2008",
        ranking: 100,
        tier: "mistake",
        poster: "imgs/posters/mcu/the incredible hulk.jpg"
    },
    {
        title: "X-Men Origins: Wolverine",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["Wolverine"],
        medium: ["Live Action"],
        year: "2009",
        ranking: 95,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/xmen origins wolverine.jpg"
    },
    {
        title: "Iron Man 2",
        type: "Movie",
        universe: ["MCU"],
        phase: ["1"],
        saga: ["Infinity"],
        franchise: ["Iron Man"],
        medium: ["Live Action"],
        year: "2010",
        ranking: 71,
        tier: "good",
        poster: "imgs/posters/mcu/iron man 2.jpg"
    },
    {
        title: "Thor",
        type: "Movie",
        universe: ["MCU"],
        phase: ["1"],
        saga: ["Infinity"],
        franchise: ["Thor"],
        medium: ["Live Action"],
        year: "2011",
        ranking: 89,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/thor.jpg"
    },
    {
        title: "X-Men: First Class",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["X-Men (Prequels)"],
        medium: ["Live Action"],
        year: "2011",
        ranking: 34,
        tier: "excellent",
        poster: "imgs/posters/mcu/xmen first class.jpg"
    },
    {
        title: "Captain America: The First Avenger",
        type: "Movie",
        universe: ["MCU"],
        phase: ["1"],
        saga: ["Infinity"],
        franchise: ["Captain America"],
        medium: ["Live Action"],
        year: "2011",
        ranking: 56,
        tier: "good",
        poster: "imgs/posters/mcu/captain america the first avenger.jpg"
    },
    {
        title: "The Consultant",
        type: "Short",
        universe: ["MCU"],
        phase: ["1"],
        saga: ["Infinity"],
        franchise: ["One Shots"],
        medium: ["Live Action"],
        year: "2011",
        ranking: 76,
        tier: "book",
        poster: "imgs/posters/mcu/the consultant.jpg"
    },
    {
        title: "A Funny Thing Happened on the Way to Thor's Hammer",
        type: "Short",
        universe: ["MCU"],
        phase: ["1"],
        saga: ["Infinity"],
        franchise: ["One Shots"],
        medium: ["Live Action"],
        year: "2011",
        ranking: 77,
        tier: "book",
        poster: "imgs/posters/mcu/a funny thing happened on the way to thors hammer.jpg"
    },
    {
        title: "The Avengers",
        type: "Movie",
        universe: ["MCU"],
        phase: ["1"],
        saga: ["Infinity"],
        franchise: ["Avengers"],
        medium: ["Live Action"],
        year: "2012",
        ranking: 22,
        tier: "best",
        poster: "imgs/posters/mcu/the avengers.jpg"
    },
    {
        title: "The Amazing Spider-Man",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: ["Spider-Man (Andrew Garfield)"],
        medium: ["Live Action"],
        year: "2012",
        ranking: 61,
        tier: "good",
        poster: "imgs/posters/mcu/the amazing spiderman.jpg"
    },
    {
        title: "Item 47",
        type: "Short",
        universe: ["MCU"],
        phase: ["1"],
        saga: ["Infinity"],
        franchise: ["One Shots"],
        medium: ["Live Action"],
        year: "2012",
        ranking: 79,
        tier: "book",
        poster: "imgs/posters/mcu/item 47.jpg"
    },
    {
        title: "Iron Man 3",
        type: "Movie",
        universe: ["MCU"],
        phase: ["2"],
        saga: ["Infinity"],
        franchise: ["Iron Man"],
        medium: ["Live Action"],
        year: "2013",
        ranking: 47,
        tier: "good",
        poster: "imgs/posters/mcu/iron man 3.jpg"
    },
    {
        title: "The Wolverine",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["Wolverine"],
        medium: ["Live Action"],
        year: "2013",
        ranking: 44,
        tier: "excellent",
        poster: "imgs/posters/mcu/the wolverine.jpg"
    },
    {
        title: "Agent Carter",
        type: "Short",
        universe: ["MCU"],
        phase: ["2"],
        saga: ["Infinity"],
        franchise: ["One Shots"],
        medium: ["Live Action"],
        year: "2013",
        ranking: 74,
        tier: "book",
        poster: "imgs/posters/mcu/agent carter.jpg"
    },
    {
        title: "Thor: The Dark World",
        type: "Movie",
        universe: ["MCU"],
        phase: ["2"],
        saga: ["Infinity"],
        franchise: ["Thor"],
        medium: ["Live Action"],
        year: "2013",
        ranking: 106,
        tier: "mistake",
        poster: "imgs/posters/mcu/thor the dark world.jpg"
    },
    {
        title: "All Hail the King",
        type: "Short",
        universe: ["MCU"],
        phase: ["2"],
        saga: ["Infinity"],
        franchise: ["One Shots"],
        medium: ["Live Action"],
        year: "2014",
        ranking: 73,
        tier: "book",
        poster: "imgs/posters/mcu/all hail the king.jpg"
    },
    {
        title: "Captain America: The Winter Soldier",
        type: "Movie",
        universe: ["MCU"],
        phase: ["2"],
        saga: ["Infinity"],
        franchise: ["Captain America"],
        medium: ["Live Action"],
        year: "2014",
        ranking: 17,
        tier: "great",
        poster: "imgs/posters/mcu/captain america the winter soldier.jpg"
    },
    {
        title: "The Amazing Spider-Man 2",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: ["Spider-Man (Andrew Garfield)"],
        medium: ["Live Action"],
        year: "2014",
        ranking: 85,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/the amazing spiderman 2.jpg"
    },
    {
        title: "X-Men: Days of Future Past",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["X-Men (Prequels)"],
        medium: ["Live Action"],
        year: "2014",
        ranking: 10,
        tier: "great",
        poster: "imgs/posters/mcu/xmen days of future past.jpg"
    },
    {
        title: "Guardians of the Galaxy",
        type: "Movie",
        universe: ["MCU"],
        phase: ["2"],
        saga: ["Infinity"],
        franchise: ["Guardians of the Galaxy"],
        medium: ["Live Action"],
        year: "2014",
        ranking: 21,
        tier: "best",
        poster: "imgs/posters/mcu/guardians of the galaxy.jpg"
    },
    {
        title: "Daredevil [Season 1]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["Daredevil (Charlie Cox)"],
        medium: ["Live Action"],
        year: "2015",
        ranking: 16,
        tier: "great",
        poster: "imgs/posters/mcu/daredevil season 1.jpg",
        episodes: [
            {number: 1, title: "Into the Ring", tier: "best"},
            {number: 2, title: "Cut Man", tier: "great"},
            {number: 3, title: "Rabbit in a Snowstorm", tier: "best"},
            {number: 4, title: "In the Blood", tier: "brilliant"},
            {number: 5, title: "World on Fire", tier: "best"},
            {number: 6, title: "Condemned", tier: "great"},
            {number: 7, title: "Stick", tier: "great"},
            {number: 8, title: "Shadows in the Glass", tier: "excellent"},
            {number: 9, title: "Speak of the Devil", tier: "great"},
            {number: 10, title: "Nelson v. Murdock", tier: "great"},
            {number: 11, title: "The Path of the Righteous", tier: "great"},
            {number: 12, title: "The Ones We Leave Behind", tier: "great"},
            {number: 13, title: "Daredevil", tier: "great"}
        ]
    },
    {
        title: "Avengers: Age of Ultron",
        type: "Movie",
        universe: ["MCU"],
        phase: ["2"],
        saga: ["Infinity"],
        franchise: ["Avengers"],
        medium: ["Live Action"],
        year: "2015",
        ranking: 36,
        tier: "excellent",
        poster: "imgs/posters/mcu/avengers age of ultron.jpg"
    },
    {
        title: "Ant-Man",
        type: "Movie",
        universe: ["MCU"],
        phase: ["2"],
        saga: ["Infinity"],
        franchise: ["Ant-Man"],
        medium: ["Live Action"],
        year: "2015",
        ranking: 54,
        tier: "good",
        poster: "imgs/posters/mcu/antman.jpg"
    },
    {
        title: "Fantastic Four (2015)",
        type: "Movie",
        universe: ["Miscellaneous"],
        phase: [],
        saga: [],
        franchise: [],
        medium: ["Live Action"],
        year: "2015",
        ranking: 114,
        tier: "blunder",
        poster: "imgs/posters/mcu/fantastic four 2015.jpg"
    },
    {
        title: "Jessica Jones [Season 1]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["Jessica Jones"],
        medium: ["Live Action"],
        year: "2015",
        ranking: 27,
        tier: "best",
        poster: "imgs/posters/mcu/jessica jones season 1.jpg",
        episodes: [
            {number: 1, title: "A.K.A. Ladies Night", tier: "excellent"},
            {number: 2, title: "A.K.A. Crush Syndrome", tier: "excellent"},
            {number: 3, title: "A.K.A. It's Called Whiskey", tier: "excellent"},
            {number: 4, title: "A.K.A. 99 Friends", tier: "best"},
            {number: 5, title: "A.K.A. The Sandwich Saved Me", tier: "best"},
            {number: 6, title: "A.K.A. You're a Winner!", tier: "best"},
            {number: 7, title: "A.K.A. Top Shelf Perverts", tier: "excellent"},
            {number: 8, title: "A.K.A. WWJD?", tier: "best"},
            {number: 9, title: "A.K.A. Sin Bin", tier: "great"},
            {number: 10, title: "A.K.A. 1,000 Cuts", tier: "great"},
            {number: 11, title: "A.K.A. I've Got the Blues", tier: "excellent"},
            {number: 12, title: "A.K.A. Take a Bloody Number", tier: "best"},
            {number: 13, title: "A.K.A. Smile", tier: "excellent"}
        ]
    },
    {
        title: "Deadpool",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["Deadpool"],
        medium: ["Live Action"],
        year: "2016",
        ranking: 24,
        tier: "best",
        poster: "imgs/posters/mcu/deadpool.jpg"
    },
    {
        title: "Daredevil [Season 2]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["Daredevil (Charlie Cox)"],
        medium: ["Live Action"],
        year: "2016",
        ranking: 30,
        tier: "best",
        poster: "imgs/posters/mcu/daredevil season 2.jpg",
        episodes: [
            {number: 1, title: "Bang", tier: "best"},
            {number: 2, title: "Dogs to a Gunfight", tier: "best"},
            {number: 3, title: "New York's Finest", tier: "brilliant"},
            {number: 4, title: "Penny and Dime", tier: "brilliant"},
            {number: 5, title: "Kinbaku", tier: "excellent"},
            {number: 6, title: "Regrets Only", tier: "excellent"},
            {number: 7, title: "Semper Fidelis", tier: "excellent"},
            {number: 8, title: "Guilty as Sin", tier: "great"},
            {number: 9, title: "Seven Minutes in Heaven", tier: "great"},
            {number: 10, title: "The Man in the Box", tier: "excellent"},
            {number: 11, title: ".380", tier: "excellent"},
            {number: 12, title: "The Dark at the End of the Tunnel", tier: "great"},
            {number: 13, title: "A Cold Day in Hell's Kitchen", tier: "best"}
        ]
    },
    {
        title: "Captain America: Civil War",
        type: "Movie",
        universe: ["MCU"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["Captain America"],
        medium: ["Live Action"],
        year: "2016",
        ranking: 13,
        tier: "great",
        poster: "imgs/posters/mcu/captain america civil war.jpg"
    },
    {
        title: "X-Men: Apocalypse",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["X-Men (Prequels)"],
        medium: ["Live Action"],
        year: "2016",
        ranking: 64,
        tier: "good",
        poster: "imgs/posters/mcu/xmen apocalypse.jpg"
    },
    {
        title: "Luke Cage [Season 1]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["Luke Cage"],
        medium: ["Live Action"],
        year: "2016",
        ranking: 93,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/luke cage season 1.jpg",
        episodes: [
            {number: 1, title: "Moment of Truth", tier: "good"},
            {number: 2, title: "Code of the Streets", tier: "excellent"},
            {number: 3, title: "Who's Gonna Take the Weight?", tier: "good"},
            {number: 4, title: "Step in the Arena", tier: "excellent"},
            {number: 5, title: "Just Get a Rep", tier: "excellent"},
            {number: 6, title: "Suckas Need Bodyguards", tier: "good"},
            {number: 7, title: "Manifest", tier: "good"},
            {number: 8, title: "Blowin' Up The Spot", tier: "good"},
            {number: 9, title: "DWCK", tier: "innacuracy"},
            {number: 10, title: "Take It Personal", tier: "innacuracy"},
            {number: 11, title: "Now You're Mine", tier: "innacuracy"},
            {number: 12, title: "Soliloquy of Chaos", tier: "innacuracy"},
            {number: 13, title: "You Know My Steez", tier: "innacuracy"}
        ]
    },
    {
        title: "Doctor Strange",
        type: "Movie",
        universe: ["MCU"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["Doctor Strange"],
        medium: ["Live Action"],
        year: "2016",
        ranking: 43,
        tier: "excellent",
        poster: "imgs/posters/mcu/doctor strange.jpg"
    },
    {
        title: "Logan",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["Wolverine"],
        medium: ["Live Action"],
        year: "2017",
        ranking: 15,
        tier: "great",
        poster: "imgs/posters/mcu/logan.jpg"
    },
    {
        title: "Iron Fist [Season 1]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["Iron Fist"],
        medium: ["Live Action"],
        year: "2017",
        ranking: 81,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/iron fist season 1.jpg",
        episodes: [
            {number: 1, title: "Snow Gives Way", tier: "good"},
            {number: 2, title: "Shadow Hawk Takes Flight", tier: "innacuracy"},
            {number: 3, title: "Rolling Thunder Cannon Punch", tier: "good"},
            {number: 4, title: "Eight Diagram Dragon Palm", tier: "innacuracy"},
            {number: 5, title: "Under Leaf Pluck Lotus", tier: "good"},
            {number: 6, title: "Immortal Emerges from Cave", tier: "good"},
            {number: 7, title: "Felling Tree with Roots", tier: "good"},
            {number: 8, title: "The Blessing of Many Fractures", tier: "innacuracy"},
            {number: 9, title: "The Mistress of All Agonies", tier: "good"},
            {number: 10, title: "Black Tiger Steals Heart", tier: "excellent"},
            {number: 11, title: "Lead Horse Back to Stable", tier: "excellent"},
            {number: 12, title: "Bar the Big Boss", tier: "excellent"},
            {number: 13, title: "Dragon Plays with Fire", tier: "good"}
        ]
    },
    {
        title: "Guardians of the Galaxy Vol. 2",
        type: "Movie",
        universe: ["MCU"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["Guardians of the Galaxy"],
        medium: ["Live Action"],
        year: "2017",
        ranking: 51,
        tier: "good",
        poster: "imgs/posters/mcu/guardians of the galaxy vol 2.jpg"
    },
    {
        title: "Spider-Man: Homecoming",
        type: "Movie",
        universe: ["MCU", "Sony Spider-Man"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["Spider-Man (Tom Holland)"],
        medium: ["Live Action"],
        year: "2017",
        ranking: 57,
        tier: "good",
        poster: "imgs/posters/mcu/spiderman homecoming.jpg"
    },
    {
        title: "The Defenders",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        year: "2017",
        franchise: [],
        medium: ["Live Action"],
        ranking: 52,
        tier: "good",
        poster: "imgs/posters/mcu/the defenders.jpg",
        episodes: [
            {number: 1, title: "The H Word", tier: "good"},
            {number: 2, title: "Mean Right Hook", tier: "good"},
            {number: 3, title: "Worst Behaviour", tier: "excellent"},
            {number: 4, title: "Royal Dragon", tier: "best"},
            {number: 5, title: "Take Shelter", tier: "good"},
            {number: 6, title: "Ashes, Ashes", tier: "excellent"},
            {number: 7, title: "Fish in the Jailhouse", tier: "excellent"},
            {number: 8, title: "The Defenders", tier: "excellent"}
        ]
    },
    {
        title: "Thor: Ragnarok",
        type: "Movie",
        universe: ["MCU"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["Thor"],
        medium: ["Live Action"],
        year: "2017",
        ranking: 55,
        tier: "good",
        poster: "imgs/posters/mcu/thor ragnarok.jpg"
    },
    {
        title: "The Punisher [Season 1]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["The Punisher"],
        medium: ["Live Action"],
        year: "2017",
        ranking: 26,
        tier: "best",
        poster: "imgs/posters/mcu/the punisher season 1.jpg",
        episodes: [
            {number: 1, title: "3 AM", tier: "excellent"},
            {number: 2, title: "Two Dead Men", tier: "excellent"},
            {number: 3, title: "Kandahar", tier: "excellent"},
            {number: 4, title: "Resupply", tier: "best"},
            {number: 5, title: "Gunner", tier: "best"},
            {number: 6, title: "The Judas Goat", tier: "excellent"},
            {number: 7, title: "Crosshairs", tier: "great"},
            {number: 8, title: "Cold Steel", tier: "excellent"},
            {number: 9, title: "Front Toward Enemy", tier: "great"},
            {number: 10, title: "Virtue of the Vicious", tier: "brilliant"},
            {number: 11, title: "Danger Close", tier: "great"},
            {number: 12, title: "Home", tier: "great"},
            {number: 13, title: "Memento Mori", tier: "great"}
        ]
    },
    {
        title: "Black Panther",
        type: "Movie",
        universe: ["MCU"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["Black Panther"],
        medium: ["Live Action"],
        year: "2018",
        ranking: 32,
        tier: "excellent",
        poster: "imgs/posters/mcu/black panther.jpg"
    },
    {
        title: "Jessica Jones [Season 2]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["Jessica Jones"],
        medium: ["Live Action"],
        year: "2018",
        ranking: 96,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/jessica jones season 2.jpg",
        episodes: [
            {number: 1, title: "A.K.A. Start at the Beginning", tier: "innacuracy"},
            {number: 2, title: "A.K.A. Freak Accident", tier: "innacuracy"},
            {number: 3, title: "A.K.A. Sole Survivor", tier: "good"},
            {number: 4, title: "A.K.A. God Help the Hobo", tier: "good"},
            {number: 5, title: "A.K.A. The Octopus", tier: "innacuracy"},
            {number: 6, title: "A.K.A. Facetime", tier: "innacuracy"},
            {number: 7, title: "A.K.A. I Want Your Cray Cray", tier: "good"},
            {number: 8, title: "A.K.A. Ain't We Got Fun", tier: "innacuracy"},
            {number: 9, title: "A.K.A. Shark in the Bathtub", tier: "innacuracy"},
            {number: 10, title: "A.K.A. Pork Chop", tier: "innacuracy"},
            {number: 11, title: "A.K.A. Three Lives and Counting", tier: "excellent"},
            {number: 12, title: "A.K.A. Pray for My Patsy", tier: "innacuracy"},
            {number: 13, title: "A.K.A. Payland", tier: "good"}
        ]
    },
    {
        title: "Avengers: Infinity War",
        type: "Movie",
        universe: ["MCU"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["Avengers"],
        medium: ["Live Action"],
        ranking: 1,
        year: "2018",
        tier: "brilliant",
        poster: "imgs/posters/mcu/avengers infinity war.jpg"
    },
    {
        title: "Deadpool 2",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["Deadpool"],
        medium: ["Live Action"],
        year: "2018",
        ranking: 37,
        tier: "excellent",
        poster: "imgs/posters/mcu/deadpool 2.jpg"
    },
    {
        title: "Luke Cage [Season 2]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["Luke Cage"],
        medium: ["Live Action"],
        year: "2018",
        ranking: 99,
        tier: "mistake",
        poster: "imgs/posters/mcu/luke cage season 2.jpg",
        episodes: [
            {number: 1, title: "Soul Brother #1", tier: "good"},
            {number: 2, title: "Straighten It Out", tier: "innacuracy"},
            {number: 3, title: "Wig Out", tier: "innacuracy"},
            {number: 4, title: "I Get Physical", tier: "innacuracy"},
            {number: 5, title: "All Souled Out", tier: "innacuracy"},
            {number: 6, title: "The Basement", tier: "mistake"},
            {number: 7, title: "On and On", tier: "innacuracy"},
            {number: 8, title: "If It Ain't Rough,It Ain't Right", tier: "mistake"},
            {number: 9, title: "For Pete's Sake", tier: "innacuracy"},
            {number: 10, title: "The Main Ingredient", tier: "good"},
            {number: 11, title: "The Creator", tier: "innacuracy"},
            {number: 12, title: "Can't Front On Me", tier: "innacuracy"},
            {number: 13, title: "They Reminisce Over You", tier: "innacuracy"}
        ]
    },
    {
        title: "Ant-Man and the Wasp",
        type: "Movie",
        universe: ["MCU"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["Ant-Man"],
        medium: ["Live Action"],
        year: "2018",
        ranking: 62,
        tier: "good",
        poster: "imgs/posters/mcu/antman and the wasp.jpg"
    },
    {
        title: "Iron Fist [Season 2]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["Iron Fist"],
        medium: ["Live Action"],
        year: "2018",
        ranking: 90,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/iron fist season 2.jpg",
        episodes: [
            {number: 1, title: "The Fury Of Iron Fist", tier: "innacuracy"},
            {number: 2, title: "The City's Not for Burning", tier: "innacuracy"},
            {number: 3, title: "This Deadly Secret...", tier: "innacuracy"},
            {number: 4, title: "Target: Iron Fist", tier: "good"},
            {number: 5, title: "Heart of the Dragon", tier: "good"},
            {number: 6, title: "The Dragon Dies at Dawn", tier: "good"},
            {number: 7, title: "Morning of the Mindstorm", tier: "innacuracy"},
            {number: 8, title: "Citadel on the Edge of Vengeance", tier: "good"},
            {number: 9, title: "War Without End", tier: "excellent"},
            {number: 10, title: "A Duel of Iron", tier: "excellent"}
        ]
    },
    {
        title: "Venom",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: ["Venom"],
        medium: ["Live Action"],
        year: "2018",
        ranking: 88,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/venom.jpg"
    },
    {
        title: "Daredevil [Season 3]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["Daredevil (Charlie Cox)"],
        medium: ["Live Action"],
        year: "2018",
        ranking: 9,
        tier: "great",
        poster: "imgs/posters/mcu/daredevil season 3.jpg",
        episodes: [
            {number: 1, title: "Resurrection", tier: "great"},
            {number: 2, title: "Please", tier: "great"},
            {number: 3, title: "No Good Deed", tier: "best"},
            {number: 4, title: "Blindsided", tier: "brilliant"},
            {number: 5, title: "The Perfect Game", tier: "great"},
            {number: 6, title: "The Devil You Know", tier: "brilliant"},
            {number: 7, title: "Aftermath", tier: "best"},
            {number: 8, title: "Upstairs/Downstairs", tier: "great"},
            {number: 9, title: "Revelations", tier: "great"},
            {number: 10, title: "Karen", tier: "great"},
            {number: 11, title: "Reunion", tier: "great"},
            {number: 12, title: "One Last Shot", tier: "great"},
            {number: 13, title: "A New Napkin", tier: "brilliant"}
        ]
    },
    {
        title: "Spider-Man: Into the Spider-Verse",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: ["Spider-Verse"],
        medium: ["Animation"],
        year: "2018",
        ranking: 12,
        tier: "great",
        poster: "imgs/posters/mcu/spiderman into the spiderverse.jpg"
    },
    {
        title: "The Punisher [Season 2]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["The Punisher"],
        medium: ["Live Action"],
        year: "2019",
        ranking: 35,
        tier: "excellent",
        poster: "imgs/posters/mcu/the punisher season 2.jpg",
        episodes: [
            {number: 1, title: "Roudhouse Blues", tier: "excellent"},
            {number: 2, title: "Fight or Flight", tier: "excellent"},
            {number: 3, title: "Trouble The Water", tier: "best"},
            {number: 4, title: "Scar Tissue", tier: "good"},
            {number: 5, title: "One-Eyed Jacks", tier: "good"},
            {number: 6, title: "Nakazat", tier: "good"},
            {number: 7, title: "One Bad Day", tier: "best"},
            {number: 8, title: "My Brother's Keeper", tier: "excellent"},
            {number: 9, title: "Flustercluck", tier: "best"},
            {number: 10, title: "The Hearts of Men", tier: "excellent"},
            {number: 11, title: "The Abyss", tier: "best"},
            {number: 12, title: "Collision Course", tier: "excellent"},
            {number: 13, title: "The Whirlwind", tier: "excellent"}
        ]
    },
    {
        title: "Captain Marvel",
        type: "Movie",
        universe: ["MCU"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["The Marvels"],
        medium: ["Live Action"],
        year: "2019",
        ranking: 63,
        tier: "good",
        poster: "imgs/posters/mcu/captain marvel.jpg"
    },
    {
        title: "Avengers: Endgame",
        type: "Movie",
        universe: ["MCU"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["Avengers"],
        medium: ["Live Action"],
        year: "2019",
        ranking: 4,
        tier: "brilliant",
        poster: "imgs/posters/mcu/avengers endgame.jpg"
    },
    {
        title: "Dark Phoenix",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: ["X-Men (Prequels)"],
        medium: ["Live Action"],
        year: "2019",
        ranking: 91,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/dark phoenix.jpg"
    },
    {
        title: "Jessica Jones [Season 3]",
        type: "TV Show",
        universe: ["MCU"],
        phase: [],
        saga: ["Defenders"],
        franchise: ["Jessica Jones"],
        medium: ["Live Action"],
        year: "2019",
        ranking: 87,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/jessica jones season 3.jpg",
        episodes: [
            {number: 1, title: "A.K.A. The Perfect Burger", tier: "innacuracy"},
            {number: 2, title: "A.K.A. You're Welcome", tier: "innacuracy"},
            {number: 3, title: "A.K.A. I Have No Spleen", tier: "good"},
            {number: 4, title: "A.K.A. Customer Service Is Standing By", tier: "good"},
            {number: 5, title: "A.K.A. I Wish", tier: "innacuracy"},
            {number: 6, title: "A.K.A. Sorry Face", tier: "innacuracy"},
            {number: 7, title: "A.K.A. The Double Half-Wappinger", tier: "good"},
            {number: 8, title: "A.K.A. Camera Friendly", tier: "good"},
            {number: 9, title: "A.K.A. I Did Something Today", tier: "innacuracy"},
            {number: 10, title: "A.K.A. Hero Pants", tier: "innacuracy"},
            {number: 11, title: "A.K.A. Hellcat", tier: "innacuracy"},
            {number: 12, title: "A.K.A. A Lotta Worms", tier: "good"},
            {number: 13, title: "A.K.A. Everything", tier: "excellent"}
        ]
    },
    {
        title: "Spider-Man: Far From Home",
        type: "Movie",
        universe: ["MCU", "Sony Spider-Man"],
        phase: ["3"],
        saga: ["Infinity"],
        franchise: ["Spider-Man (Tom Holland)"],
        medium: ["Live Action"],
        year: "2019",
        ranking: 49,
        tier: "good",
        poster: "imgs/posters/mcu/spiderman far from home.jpg"
    },
    {
        title: "The New Mutants",
        type: "Movie",
        universe: ["Fox X-Men"],
        phase: [],
        saga: [],
        franchise: [],
        medium: ["Live Action"],
        year: "2020",
        ranking: 102,
        tier: "mistake",
        poster: "imgs/posters/mcu/the new mutants.jpg"
    },
    {
        title: "WandaVision",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["WandaVision"],
        medium: ["Live Action"],
        year: "2021",
        ranking: 5,
        tier: "great",
        poster: "imgs/posters/mcu/wandavision.jpg",
        episodes: [
            {number: 1, title: "Filmed Before a Live Studio Audience", tier: "great"},
            {number: 2, title: "Don't Touch That Dial", tier: "great"},
            {number: 3, title: "Now in Colour", tier: "great"},
            {number: 4, title: "We Interrupt This Program", tier: "brilliant"},
            {number: 5, title: "On a Very Special Episode...", tier: "brilliant"},
            {number: 6, title: "All-New Halloween Spooktacular!", tier: "brilliant"},
            {number: 7, title: "Breaking the Fourth Wall", tier: "great"},
            {number: 8, title: "Previously On", tier: "brilliant"},
            {number: 9, title: "The Series Finale", tier: "best"}
        ]
    },
    {
        title: "The Falcon and the Winter Soldier",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["Captain America"],
        medium: ["Live Action"],
        year: "2021",
        ranking: 58,
        tier: "good",
        poster: "imgs/posters/mcu/the falcon and the winter soldier.jpg",
        episodes: [
            {number: 1, title: "New World Order", tier: "excellent"},
            {number: 2, title: "The Star-Spangled Man", tier: "good"},
            {number: 3, title: "Power Broker", tier: "good"},
            {number: 4, title: "The Whole World Is Watching", tier: "excellent"},
            {number: 5, title: "Truth", tier: "good"},
            {number: 6, title: "One World, One People", tier: "good"}
        ]
    },
    {
        title: "Loki [Season 1]",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["Loki"],
        medium: ["Live Action"],
        year: "2021",
        ranking: 8,
        tier: "great",
        poster: "imgs/posters/mcu/loki season 1.jpg",
        episodes: [
            {number: 1, title: "Glorious Purpose", tier: "great"},
            {number: 2, title: "The Variant", tier: "great"},
            {number: 3, title: "Lamentis", tier: "best"},
            {number: 4, title: "The Nexus Event", tier: "great"},
            {number: 5, title: "Journey Into Mystery", tier: "best"},
            {number: 6, title: "For All Time. Always.", tier: "brilliant"}
        ]
    },
    {
        title: "Black Widow",
        type: "Movie",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        year: "2021",
        franchise: [],
        medium: ["Live Action"],
        ranking: 48,
        tier: "good",
        poster: "imgs/posters/mcu/black widow.jpg"
    },
    {
        title: "What If...? [Season 1]",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["What If...?"],
        medium: ["Animation"],
        year: "2021",
        ranking: 108,
        tier: "miss",
        poster: "imgs/posters/mcu/what if season 1.jpg",
        episodes: [
            {number: 1, title: "What If... Captain Carter Were The First Avenger?", tier: "innacuracy"},
            {number: 2, title: "What If... T'Challa became a Star-Lord?", tier: "innacuracy"},
            {number: 3, title: "What If... the world lost Its mightiest heroes?", tier: "innacuracy"},
            {number: 4, title: "What If... Doctor Strange lost his heart instead of his hands?", tier: "good"},
            {number: 5, title: "What If... zombies!?", tier: "innacuracy"},
            {number: 6, title: "What If... Killmonger rescued Tony Stark?", tier: "mistake"},
            {number: 7, title: "What If... Thor were an only child?", tier: "blunder"},
            {number: 8, title: "What If... Ultron won?", tier: "good"},
            {number: 9, title: "What If... The Watcher broke his oath?", tier: "mistake"}
        ]
    },
    {
        title: "Shang-Chi and the Legend of the Ten Rings",
        type: "Movie",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        year: "2021",
        franchise: [],
        medium: ["Live Action"],
        ranking: 18,
        tier: "best",
        poster: "imgs/posters/mcu/shangchi and the legend of the ten rings.jpg"
    },
    {
        title: "Venom: Let There Be Carnage",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: ["Venom"],
        medium: ["Live Action"],
        year: "2021",
        ranking: 97,
        tier: "mistake",
        poster: "imgs/posters/mcu/venom let there be carnage.jpg"
    },
    {
        title: "Eternals",
        type: "Movie",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2021",
        ranking: 53,
        tier: "good",
        poster: "imgs/posters/mcu/eternals.jpg"
    },
    {
        title: "Hawkeye",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2021",
        ranking: 59,
        tier: "good",
        poster: "imgs/posters/mcu/hawkeye.jpg",
        episodes: [
            {number: 1, title: "Never Meet Your Heroes", tier: "good"},
            {number: 2, title: "Hide and Seek", tier: "good"},
            {number: 3, title: "Echoes", tier: "good"},
            {number: 4, title: "Partners, Am I Right?", tier: "excellent"},
            {number: 5, title: "Ronin", tier: "excellent"},
            {number: 6, title: "So This Is Christmas?", tier: "excellent"}
        ]
    },
    {
        title: "Spider-Man: No Way Home",
        type: "Movie",
        universe: ["MCU", "Sony Spider-Man"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["Spider-Man (Tom Holland)"],
        medium: ["Live Action"],
        year: "2021",
        ranking: 6,
        tier: "great",
        poster: "imgs/posters/mcu/spiderman no way home.jpg"
    },
    {
        title: "Moon Knight",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2022",
        ranking: 40,
        tier: "excellent",
        poster: "imgs/posters/mcu/moon knight.jpg",
        episodes: [
            {number: 1, title: "The Goldfish Problem", tier: "best"},
            {number: 2, title: "Summon the Suit", tier: "excellent"},
            {number: 3, title: "The Friendly Type", tier: "excellent"},
            {number: 4, title: "The Tomb", tier: "great"},
            {number: 5, title: "Asylum", tier: "best"},
            {number: 6, title: "Gods and Monsters", tier: "good"}
        ]
    },
    {
        title: "Morbius",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: [],
        medium: ["Live Action"],
        year: "2022",
        ranking: 112,
        tier: "blunder",
        poster: "imgs/posters/mcu/morbius.jpg"
    },
    {
        title: "Doctor Strange in the Multiverse of Madness",
        type: "Movie",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["Doctor Strange"],
        medium: ["Live Action"],
        year: "2022",
        ranking: 41,
        tier: "excellent",
        poster: "imgs/posters/mcu/doctor strange in the multiverse of madness.jpg"
    },
    {
        title: "Ms. Marvel",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["The Marvels"],
        medium: ["Live Action"],
        year: "2022",
        ranking: 66,
        tier: "good",
        poster: "imgs/posters/mcu/ms marvel.jpg",
        episodes: [
            {number: 1, title: "Generation Why", tier: "good"},
            {number: 2, title: "Crushed", tier: "good"},
            {number: 3, title: "Destined", tier: "excellent"},
            {number: 4, title: "Seeing Red", tier: "good"},
            {number: 5, title: "Time and Again", tier: "good"},
            {number: 6, title: "No Normal", tier: "good"}
        ]
    },
    {
        title: "Thor: Love and Thunder",
        type: "Movie",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["Thor"],
        medium: ["Live Action"],
        year: "2022",
        ranking: 98,
        tier: "mistake",
        poster: "imgs/posters/mcu/thor love and thunder.jpg"
    },
    {
        title: "I Am Groot [Season 1]",
        type: "Short",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["I Am Groot"],
        medium: ["Animation"],
        year: "2022",
        ranking: 75,
        tier: "book",
        poster: "imgs/posters/mcu/i am groot season 1.jpg",
        episodes: [
            {number: 1, title: "Groot's First Steps", tier: "book"},
            {number: 2, title: "The Little Guy", tier: "book"},
            {number: 3, title: "Groot's Pursuit", tier: "book"},
            {number: 4, title: "Groot Takes a Bath", tier: "book"},
            {number: 5, title: "Magnum Opus", tier: "book"}
        ]
    },
    {
        title: "She-Hulk: Attorney at Law",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2022",
        ranking: 105,
        tier: "mistake",
        poster: "imgs/posters/mcu/shehulk attorney at law.jpg",
        episodes: [
            {number: 1, title: "A Normal Amount of Rage", tier: "good"},
            {number: 2, title: "Superhuman Law", tier: "innacuracy"},
            {number: 3, title: "The People vs. Emil Blonsky", tier: "innacuracy"},
            {number: 4, title: "Is This Not Real Magic?", tier: "good"},
            {number: 5, title: "Mean, Green, and Straight Poured into These Jeans", tier: "mistake"},
            {number: 6, title: "Just Jen", tier: "blunder"},
            {number: 7, title: "The Retreat", tier: "mistake"},
            {number: 8, title: "Ribbit and Rip it", tier: "excellent"},
            {number: 9, title: "Whose Show is This?", tier: "good"}
        ]
    },
    {
        title: "Werewolf By Night",
        type: "Special Presentation",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2022",
        ranking: 45,
        tier: "excellent",
        poster: "imgs/posters/mcu/werewolf by night.jpg"
    },
    {
        title: "Black Panther: Wakanda Forever",
        type: "Movie",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["Black Panther"],
        medium: ["Live Action"],
        year: "2022",
        ranking: 42,
        tier: "excellent",
        poster: "imgs/posters/mcu/black panther wakanda forever.jpg"
    },
    {
        title: "The Guardians of the Galaxy Holiday Special",
        type: "Special Presentation",
        universe: ["MCU"],
        phase: ["4"],
        saga: ["Multiverse"],
        franchise: ["Guardians of the Galaxy"],
        medium: ["Live Action"],
        year: "2022",
        ranking: 46,
        tier: "excellent",
        poster: "imgs/posters/mcu/the guardians of the galaxy holiday special.jpg"
    },
    {
        title: "Ant-Man and the Wasp: Quantumania",
        type: "Movie",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["Ant-Man"],
        medium: ["Live Action"],
        year: "2023",
        ranking: 69,
        tier: "good",
        poster: "imgs/posters/mcu/antman and the wasp quantumania.jpg"
    },
    {
        title: "Guardians of the Galaxy Vol. 3",
        type: "Movie",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["Guardians of the Galaxy"],
        medium: ["Live Action"],
        year: "2023",
        ranking: 11,
        tier: "great",
        poster: "imgs/posters/mcu/guardians of the galaxy vol 3.jpg"
    },
    {
        title: "Spider-Man: Across the Spider-Verse",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: ["Spider-Verse"],
        medium: ["Animation"],
        year: "2023",
        ranking: 2,
        tier: "brilliant",
        poster: "imgs/posters/mcu/spiderman across the spiderverse.jpg"
    },
    {
        title: "Secret Invasion",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2023",
        ranking: 109,
        tier: "miss",
        poster: "imgs/posters/mcu/secret invasion.jpg",
        episodes: [
            {number: 1, title: "Resurrection", tier: "mistake"},
            {number: 2, title: "Promises", tier: "innacuracy"},
            {number: 3, title: "Betrayed", tier: "innacuracy"},
            {number: 4, title: "Beloved", tier: "innacuracy"},
            {number: 5, title: "Harvest", tier: "innacuracy"},
            {number: 6, title: "Home", tier: "blunder"}
        ]
    },
    {
        title: "I Am Groot [Season 2]",
        type: "Short",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["I Am Groot"],
        medium: ["Animation"],
        year: "2023",
        ranking: 78,
        tier: "book",
        poster: "imgs/posters/mcu/i am groot season 2.jpg",
        episodes: [
            {number: 1, title: "Are You My Groot?", tier: "book"},
            {number: 2, title: "Groot Noses Around", tier: "book"},
            {number: 3, title: "Groot's Snow Day", tier: "book"},
            {number: 4, title: "Groot's Sweet Treat", tier: "book"},
            {number: 5, title: "Groot and the Great Prophecy", tier: "innacuracy"}
        ]
    },
    {
        title: "Loki [Season 2]",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["Loki"],
        medium: ["Live Action"],
        year: "2023",
        ranking: 3,
        tier: "brilliant",
        poster: "imgs/posters/mcu/loki season 2.jpg",
        episodes: [
            {number: 1, title: "Ouroboros", tier: "brilliant"},
            {number: 2, title: "Breaking Brad", tier: "great"},
            {number: 3, title: "1893", tier: "great"},
            {number: 4, title: "Heart of the TVA", tier: "brilliant"},
            {number: 5, title: "Science/Fiction", tier: "brilliant"},
            {number: 6, title: "Glorious Purpose", tier: "brilliant"}
        ]
    },
    {
        title: "The Marvels",
        type: "Movie",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["The Marvels"],
        medium: ["Live Action"],
        year: "2023",
        ranking: 82,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/the marvels.jpg"
    },
    {
        title: "What If...? [Season 2]",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["What If...?"],
        medium: ["Animation"],
        year: "2023",
        ranking: 110,
        tier: "blunder",
        poster: "imgs/posters/mcu/what if season 2.jpg",
        episodes: [
            {number: 1, title: "What If... Nebula Joined the Nova Corps?", tier: "innacuracy"},
            {number: 2, title: "What If... Peter Quill Attacked Earth's Mightiest Heroes?", tier: "innacuracy"},
            {number: 3, title: "What If... Happy Hogan Saved Christmas?", tier: "blunder"},
            {number: 4, title: "What If... Iron Man Crashed Into the Grandmaster?", tier: "innacuracy"},
            {number: 5, title: "What If... Captain Carter Fought the Hydra Stomper?", tier: "innacuracy"},
            {number: 6, title: "What If... Kahhori Reshaped the World?", tier: "mistake"},
            {number: 7, title: "What If... Hela Found the Ten Rings?", tier: "innacuracy"},
            {number: 8, title: "What If... the Avengers Assembled in 1602?", tier: "innacuracy"},
            {number: 9, title: "What If... Strange Supreme Intervened?", tier: "blunder"}
        ]
    },
    {
        title: "Echo",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["Daredevil (Charlie Cox)"],
        medium: ["Live Action"],
        year: "2024",
        ranking: 92,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/echo.jpg",
        episodes: [
            {number: 1, title: "Chafa", tier: "good"},
            {number: 2, title: "Lowak", tier: "innacuracy"},
            {number: 3, title: "Tuklo", tier: "innacuracy"},
            {number: 4, title: "Taloa", tier: "good"},
            {number: 5, title: "Maya", tier: "innacuracy"}
        ]
    },
    {
        title: "Madame Web",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: [],
        medium: ["Live Action"],
        year: "2024",
        ranking: 111,
        tier: "blunder",
        poster: "imgs/posters/mcu/madame web.jpg"
    },
    {
        title: "Deadpool & Wolverine",
        type: "Movie",
        universe: ["MCU", "Fox X-Men"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["Deadpool"],
        medium: ["Live Action"],
        year: "2024",
        ranking: 20,
        tier: "best",
        poster: "imgs/posters/mcu/deadpool and wolverine.jpg"
    },
    {
        title: "Agatha All Along",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["WandaVision"],
        medium: ["Live Action"],
        year: "2024",
        ranking: 23,
        tier: "best",
        poster: "imgs/posters/mcu/agatha all along.jpg",
        episodes: [
            {number: 1, title: "Seekest Thou the Road", tier: "good"},
            {number: 2, title: "Circle Sewn With Fate / Unlock Thy Hidden Gate", tier: "innacuracy"},
            {number: 3, title: "Through Many Miles / Of Tricks and Trials", tier: "innacuracy"},
            {number: 4, title: "If I Can't Reach You / Let My Song Teach You", tier: "mistake"},
            {number: 5, title: "Darkest Hour / Wake Thy Power", tier: "excellent"},
            {number: 6, title: "Familiar by Thy Side", tier: "great"},
            {number: 7, title: "Death's Hand in Mine", tier: "brilliant"},
            {number: 8, title: "Follow Me My Friend / To Glory at the End", tier: "great"},
            {number: 9, title: "Maiden Mother Crone", tier: "best"}
        ]
    },
    {
        title: "Venom: The Last Dance",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: ["Venom"],
        medium: ["Live Action"],
        year: "2024",
        ranking: 86,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/venom the last dance.jpg"
    },
    {
        title: "Kraven the Hunter",
        type: "Movie",
        universe: ["Sony Spider-Man"],
        phase: [],
        saga: [],
        franchise: [],
        medium: ["Live Action"],
        year: "2024",
        ranking: 84,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/kraven the hunter.jpg"
    },
    {
        title: "What If...? [Season 3]",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["What If...?"],
        medium: ["Animation"],
        year: "2024",
        ranking: 113,
        tier: "blunder",
        poster: "imgs/posters/mcu/what if season 3.jpg",
        episodes: [
            {number: 1, title: "What If... The Hulk Fought the Mech Avengers?", tier: "mistake"},
            {number: 2, title: "What If... Agatha Went to Hollywood?", tier: "innacuracy"},
            {number: 3, title: "What If... The Red Guardian Stopped the Winter Soldier?", tier: "innacuracy"},
            {number: 4, title: "What If... Howard the Duck Got Hitched?", tier: "mistake"},
            {number: 5, title: "What If... The Emergence Destroyed the Earth?", tier: "mistake"},
            {number: 6, title: "What If... 1872?", tier: "innacuracy"},
            {number: 7, title: "What If... The Watcher Disappeared?", tier: "blunder"},
            {number: 8, title: "What If... What If?", tier: "blunder"}
        ]
    },
    {
        title: "Your Friendly Neighborhood Spider-Man [Season 1]",
        type: "TV Show",
        universe: ["Miscellaneous"],
        phase: [],
        saga: [],
        franchise: ["Spider-Man (YFNSM)"],
        medium: ["Animation"],
        year: "2025",
        ranking: 50,
        tier: "good",
        poster: "imgs/posters/mcu/your friendly neighborhood spiderman season 1.jpg",
        episodes: [
            {number: 1, title: "Amazing Fantasy", tier: "innacuracy"},
            {number: 2, title: "The Parker Luck", tier: "innacuracy"},
            {number: 3, title: "Secret Identity Crisis", tier: "good"},
            {number: 4, title: "Hitting the Big Time", tier: "innacuracy"},
            {number: 5, title: "The Unicorn Unleashed!", tier: "good"},
            {number: 6, title: "Duel With the Devil", tier: "excellent"},
            {number: 7, title: "Scorpion Rising", tier: "excellent"},
            {number: 8, title: "Tangled Web", tier: "good"},
            {number: 9, title: "Hero or Menace", tier: "excellent"},
            {number: 10, title: "If This Be My Destiny...", tier: "best"},
        ]
    },
    {
        title: "Captain America: Brave New World",
        type: "Movie",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["Captain America"],
        medium: ["Live Action"],
        year: "2025",
        ranking: 70,
        tier: "good",
        poster: "imgs/posters/mcu/captain america brave new world.jpg"
    },
    {
        title: "Daredevil: Born Again [Season 1]",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: ["Daredevil (Charlie Cox)"],
        medium: ["Live Action"],
        year: "2025",
        ranking: 39,
        tier: "excellent",
        poster: "imgs/posters/mcu/daredevil born again season 1.jpg",
        episodes: [
            {number: 1, title: "Heaven's Half Hour", tier: "best"},
            {number: 2, title: "Optics", tier: "good"},
            {number: 3, title: "The Hollow of His Hand", tier: "best"},
            {number: 4, title: "Sic Semper Systema", tier: "excellent"},
            {number: 5, title: "With Interest", tier: "good"},
            {number: 6, title: "Excessive Force", tier: "excellent"},
            {number: 7, title: "Art for Art's Sake", tier: "excellent"},
            {number: 8, title: "Isle of Joy", tier: "great"},
            {number: 9, title: "Straight to Hell", tier: "great"}
        ]
    },
    {
        title: "Thunderbolts*",
        type: "Movie",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2025",
        ranking: 7,
        tier: "great",
        poster: "imgs/posters/mcu/thunderbolts.jpg"
    },
    {
        title: "Ironheart",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["5"],
        saga: ["Multiverse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2025",
        ranking: 72,
        tier: "good",
        poster: "imgs/posters/mcu/ironheart.jpg",
        episodes: [
            {number: 1, title: "Take Me Home", tier: "innacuracy"},
            {number: 2, title: "Will the Real Natalie Please Stand Up?", tier: "innacuracy"},
            {number: 3, title: "We in Danger, Girl", tier: "good"},
            {number: 4, title: "Bad Magic", tier: "good"},
            {number: 5, title: "Karma's a Glitch", tier: "innacuracy"},
            {number: 6, title: "The Past Is the Past", tier: "excellent"}
        ]
    },
    {
        title: "The Fantastic Four: First Steps",
        type: "Movie",
        universe: ["MCU"],
        phase: ["6"],
        saga: ["Multiverse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2025",
        ranking: 19,
        tier: "best",
        poster: "imgs/posters/mcu/the fantastic four first steps.jpg"
    },
    {
        title: "Eyes of Wakanda",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["6"],
        saga: ["Multiverse"],
        franchise: ["Black Panther"],
        medium: ["Animation"],
        year: "2025",
        ranking: 94,
        tier: "innacuracy",
        poster: "imgs/posters/mcu/eyes of wakanda.jpg",
        episodes: [
            {number: 1, title: "Into the Lion's Den", tier: "innacuracy"},
            {number: 2, title: "Legends and Lies", tier: "innacuracy"},
            {number: 3, title: "Lost and Found", tier: "mistake"},
            {number: 4, title: "The Last Panther", tier: "good"}
        ]
    },
    {
        title: "Marvel Zombies [Season 1]",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["6"],
        saga: ["Multiverse"],
        franchise: ["What If...?"],
        medium: ["Animation"],
        year: "2025",
        ranking: 103,
        tier: "mistake",
        poster: "imgs/posters/mcu/marvel zombies season 1.jpg",
        episodes: [
            {number: 1, title: "Episode 1", tier: "innacuracy"},
            {number: 2, title: "Episode 2", tier: "good"},
            {number: 3, title: "Episode 3", tier: "good"},
            {number: 4, title: "Episode 4", tier: "blunder"}
        ]
    },
    {
        title: "Wonder Man [Season 1]",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["6"],
        saga: ["Multiverse"],
        franchise: ["Wonder Man"],
        medium: ["Live Action"],
        year: "2026",
        ranking: 31,
        tier: "best",
        poster: "imgs/posters/mcu/wonder man season 1.jpg",
        episodes: [
            {number: 1, title: "Matinee", tier: "excellent"},
            {number: 2, title: "Self-Tape", tier: "excellent"},
            {number: 3, title: "Pacomia", tier: "excellent"},
            {number: 4, title: "Doorman", tier: "great"},
            {number: 5, title: "Found Footage", tier: "excellent"},
            {number: 6, title: "Callback", tier: "great"},
            {number: 7, title: "Kathy Friedman", tier: "best"},
            {number: 8, title: "Yucca Valley", tier: "great"}
        ]
    },
    {
        title: "Daredevil: Born Again [Season 2]",
        type: "TV Show",
        universe: ["MCU"],
        phase: ["6"],
        saga: ["Multiverse"],
        franchise: ["Daredevil (Charlie Cox)"],
        medium: ["Live Action"],
        year: "2026",
        ranking: 14,
        tier: "great",
        poster: "imgs/posters/mcu/daredevil born again season 2.jpg",
        episodes: [
            {number: 1, title: "The Northern Star", tier: "best"},
            {number: 2, title: "Shoot the Moon", tier: "excellent"},
            {number: 3, title: "The Scales & The Sword", tier: "great"},
            {number: 4, title: "Gloves Off", tier: "great"},
            {number: 5, title: "The Grand Design", tier: "brilliant"},
            {number: 6, title: "Requiem", tier: "brilliant"},
            {number: 7, title: "The Hateful Darkness", tier: "great"},
            {number: 8, title: "The Southern Cross", tier: "brilliant"}
        ]
    }
]