const entries = [
    {
        title: "For All Mankind [Season 1]",
        type: "TV Show",
        saga: [],
        franchise: ["For All Mankind"],
        medium: [],
        year: "2019",
        ranking: 8,
        timeline: 1,
        tier: "best",
        poster: "imgs/posters/apple tv/for all mankind season 1.jpg",
        episodes: [
            {number: 1, title: "Red Moon", tier: "great"},
            {number: 2, title: "He Built the Saturn V", tier: "excellent"},
            {number: 3, title: "Nixon's Women", tier: "best"},
            {number: 4, title: "Prime Crew", tier: "excellent"},
            {number: 5, title: "Into the Abyss", tier: "great"},
            {number: 6, title: "Home Again", tier: "excellent"},
            {number: 7, title: "Hi Bob", tier: "great"},
            {number: 8, title: "Rupture", tier: "best"},
            {number: 9, title: "Bent Bird", tier: "great"},
            {number: 10, title: "A City Upon a Hill", tier: "great"},
        ]
    },
    {
        title: "For All Mankind [Season 2]",
        type: "TV Show",
        saga: [],
        franchise: ["For All Mankind"],
        medium: [],
        year: "2021",
        ranking: 3,
        timeline: 2,
        tier: "great",
        poster: "imgs/posters/apple tv/for all mankind season 2.jpg",
        episodes: [
            {number: 1, title: "Every Little Thing", tier: "brilliant"},
            {number: 2, title: "The Bleeding Edge", tier: "excellent"},
            {number: 3, title: "Rules of Engagement", tier: "excellent"},
            {number: 4, title: "Pathfinder", tier: "excellent"},
            {number: 5, title: "The Weight", tier: "best"},
            {number: 6, title: "Best-Laid Plans", tier: "excellent"},
            {number: 7, title: "Don't Be Cruel", tier: "best"},
            {number: 8, title: "And Here's to You", tier: "great"},
            {number: 9, title: "Triage", tier: "great"},
            {number: 10, title: "The Grey", tier: "brilliant"},
        ]
    },
    {
        title: "Coda",
        type: "Movie",
        saga: [],
        franchise: [],
        medium: [],
        year: "2021",
        ranking: 21,
        timeline: 3,
        tier: "good",
        poster: "imgs/posters/apple tv/coda.jpg"
    },
    {
        title: "Foundation [Season 1]",
        type: "TV Show",
        saga: [],
        franchise: ["Foundation"],
        medium: [],
        year: "2021",
        ranking: 19,
        timeline: 4,
        tier: "excellent",
        poster: "imgs/posters/apple tv/foundation season 1.jpg",
        episodes: [
            {number: 1, title: "The Emperor's Peace", tier: "excellent"},
            {number: 2, title: "Preparing to Live", tier: "excellent"},
            {number: 3, title: "The Mathematician's Ghost", tier: "excellent"},
            {number: 4, title: "Barbarians at the Gate", tier: "best"},
            {number: 5, title: "Upon Awakening", tier: "excellent"},
            {number: 6, title: "Death and the Maiden", tier: "excellent"},
            {number: 7, title: "Mysteries and Martyrs", tier: "excellent"},
            {number: 8, title: "The Missing Piece", tier: "good"},
            {number: 9, title: "The First Crisis", tier: "best"},
            {number: 10, title: "The Leap", tier: "great"},
        ]
    },
    {
        title: "Severance [Season 1]",
        type: "TV Show",
        saga: [],
        franchise: ["Severance"],
        medium: [],
        year: "2022",
        ranking: 6,
        timeline: 5,
        tier: "great",
        poster: "imgs/posters/apple tv/severance season 1.jpg",
        episodes: [
            {number: 1, title: "Good News About Hell", tier: "great"},
            {number: 2, title: "Half Loop", tier: "best"},
            {number: 3, title: "In Perpetuity", tier: "best"},
            {number: 4, title: "The You You Are", tier: "best"},
            {number: 5, title: "The Grim Barbarity of Optics and Design", tier: "best"},
            {number: 6, title: "Hide and Seek", tier: "best"},
            {number: 7, title: "Defiant Jazz", tier: "great"},
            {number: 8, title: "What's for Dinner?", tier: "great"},
            {number: 9, title: "The We We Are", tier: "brilliant"},
        ]
    },
    {
        title: "For All Mankind [Season 3]",
        type: "TV Show",
        saga: [],
        franchise: ["For All Mankind"],
        medium: [],
        year: "2022",
        ranking: 1,
        timeline: 6,
        tier: "great",
        poster: "imgs/posters/apple tv/for all mankind season 3.jpg",
        episodes: [
            {number: 1, title: "Polaris", tier: "brilliant"},
            {number: 2, title: "Game Changer", tier: "excellent"},
            {number: 3, title: "All In", tier: "best"},
            {number: 4, title: "Happy Valley", tier: "brilliant"},
            {number: 5, title: "Seven Minutes of Terror", tier: "brilliant"},
            {number: 6, title: "New Eden", tier: "excellent"},
            {number: 7, title: "Bring It Down", tier: "great"},
            {number: 8, title: "The Sands of Ares", tier: "excellent"},
            {number: 9, title: "Coming Home", tier: "great"},
            {number: 10, title: "Stranger in a Strange Land", tier: "brilliant"},
        ]
    },
    {
        title: "Tetris",
        type: "Movie",
        saga: [],
        franchise: [],
        medium: [],
        year: "2023",
        ranking: 4,
        timeline: 7,
        tier: "great",
        poster: "imgs/posters/apple tv/tetris.jpg"
    },
    {
        title: "Silo [Season 1]",
        type: "TV Show",
        saga: [],
        franchise: ["Silo"],
        medium: [],
        year: "2023",
        ranking: 13,
        timeline: 8,
        tier: "best",
        poster: "imgs/posters/apple tv/silo season 1.jpg",
        episodes: [
            {number: 1, title: "Freedom Day", tier: "best"},
            {number: 2, title: "Holston's Pick", tier: "excellent"},
            {number: 3, title: "Machines", tier: "excellent"},
            {number: 4, title: "Truth", tier: "good"},
            {number: 5, title: "The Janotor's Boy", tier: "excellent"},
            {number: 6, title: "The Relic", tier: "best"},
            {number: 7, title: "The Flamekeepers", tier: "excellent"},
            {number: 8, title: "Hanna", tier: "best"},
            {number: 9, title: "The Getaway", tier: "excellent"},
            {number: 10, title: "Outside", tier: "great"},
        ]
    },
    {
        title: "Hijack [Season 1]",
        type: "TV Show",
        saga: [],
        franchise: ["Hijack"],
        medium: [],
        year: "2023",
        ranking: 18,
        timeline: 9,
        tier: "excellent",
        poster: "imgs/posters/apple tv/hijack season 1.jpg",
        episodes: [
            {number: 1, title: "Final Call", tier: "excellent"},
            {number: 2, title: "3 Degrees", tier: "best"},
            {number: 3, title: "Draw a Blank", tier: "excellent"},
            {number: 4, title: "Not Responding", tier: "excellent"},
            {number: 5, title: "Less Than an Hour", tier: "best"},
            {number: 6, title: "Comply Slowly", tier: "great"},
            {number: 7, title: "Brace Brace Brace", tier: "best"},
        ]
    },
    {
        title: "Foundation [Season 2]",
        type: "TV Show",
        saga: [],
        franchise: ["Foundation"],
        medium: [],
        year: "2023",
        ranking: 16,
        timeline: 10,
        tier: "excellent",
        poster: "imgs/posters/apple tv/foundation season 2.jpg",
        episodes: [
            {number: 1, title: "In Seldon's Shadow", tier: "excellent"},
            {number: 2, title: "A Glimpse of Darkness", tier: "excellent"},
            {number: 3, title: "King and Commoner", tier: "excellent"},
            {number: 4, title: "Where the Stars are Scattered Thinly", tier: "best"},
            {number: 5, title: "The Sighted and the Seen", tier: "excellent"},
            {number: 6, title: "Why the Gods Made Wine", tier: "excellent"},
            {number: 7, title: "A Necessary Death", tier: "excellent"},
            {number: 8, title: "The Last Empress", tier: "best"},
            {number: 9, title: "Long Ago, Not Far Away", tier: "great"},
            {number: 10, title: "Creation Myths", tier: "great"},
        ]
    },
    {
        title: "For All Mankind [Season 4]",
        type: "TV Show",
        saga: [],
        franchise: ["For All Mankind"],
        medium: [],
        year: "2023",
        ranking: 9,
        timeline: 11,
        tier: "best",
        poster: "imgs/posters/apple tv/for all mankind season 4.jpg",
        episodes: [
            {number: 1, title: "Glasnot", tier: "great"},
            {number: 2, title: "Have a Nice Sol", tier: "excellent"},
            {number: 3, title: "The Bear Hug", tier: "excellent"},
            {number: 4, title: "House Divided", tier: "excellent"},
            {number: 5, title: "Goldilocks", tier: "best"},
            {number: 6, title: "Leningrad", tier: "best"},
            {number: 7, title: "Crossing the Line", tier: "excellent"},
            {number: 8, title: "Legacy", tier: "excellent"},
            {number: 9, title: "Brazil", tier: "great"},
            {number: 10, title: "Perestroika", tier: "brilliant"},
        ]
    },
    {
        title: "Dark Matter [Season 1]",
        type: "TV Show",
        saga: [],
        franchise: ["Dark Matter"],
        medium: [],
        year: "2024",
        ranking: 5,
        timeline: 12,
        tier: "great",
        poster: "imgs/posters/apple tv/dark matter season 1.jpg",
        episodes: [
            {number: 1, title: "Are You Happy in Your Life?", tier: "best"},
            {number: 2, title: "Trip of a Lifetime", tier: "best"},
            {number: 3, title: "The Box", tier: "excellent"},
            {number: 4, title: "The Corridor", tier: "excellent"},
            {number: 5, title: "Worldless", tier: "best"},
            {number: 6, title: "Superposition", tier: "best"},
            {number: 7, title: "In the Fires of Dead Stars", tier: "great"},
            {number: 8, title: "Jupiter", tier: "brilliant"},
            {number: 9, title: "Entanglement", tier: "brilliant"},
        ]
    },
    {
        title: "Sunny",
        type: "TV Show",
        saga: [],
        franchise: [],
        medium: [],
        year: "2024",
        ranking: 22,
        timeline: 13,
        tier: "good",
        poster: "imgs/posters/apple tv/sunny.jpg",
        episodes: [
            {number: 1, title: "He's in Refrigerators", tier: "excellent"},
            {number: 2, title: "Don't Blame the Machine", tier: "excellent"},
            {number: 3, title: "Mmmm, Hinoki", tier: "good"},
            {number: 4, title: "Sticky", tier: "good"},
            {number: 5, title: "Joey Sakamoto", tier: "innacuracy"},
            {number: 6, title: "Kyoto Manju, So Delicious", tier: "good"},
            {number: 7, title: "There's Been a Shift", tier: "good"},
            {number: 8, title: "Trash or Not-Trash", tier: "good"},
            {number: 9, title: "Who's in the Box", tier: "innacuracy"},
            {number: 10, title: "The Dark Manual", tier: "good"},
        ]
    },
    {
        title: "The Instigators",
        type: "Movie",
        saga: [],
        franchise: [],
        medium: [],
        year: "2024",
        ranking: 24,
        timeline: 14,
        tier: "innacuracy",
        poster: "imgs/posters/apple tv/the instigators.jpg"
    },
    {
        title: "Silo [Season 2]",
        type: "TV Show",
        saga: [],
        franchise: ["Silo"],
        medium: [],
        year: "2024",
        ranking: 10,
        timeline: 15,
        tier: "best",
        poster: "imgs/posters/apple tv/silo season 2.jpg",
        episodes: [
            {number: 1, title: "The Engineer", tier: "great"},
            {number: 2, title: "Order", tier: "excellent"},
            {number: 3, title: "Solo", tier: "excellent"},
            {number: 4, title: "The Harmonium", tier: "best"},
            {number: 5, title: "Descent", tier: "excellent"},
            {number: 6, title: "Barricades", tier: "good"},
            {number: 7, title: "The Dive", tier: "best"},
            {number: 8, title: "The Book of Quinn", tier: "best"},
            {number: 9, title: "The Safeguard", tier: "best"},
            {number: 10, title: "Into the Fire", tier: "great"},
        ]
    },
    {
        title: "Severance [Season 2]",
        type: "TV Show",
        saga: [],
        franchise: ["Severance"],
        medium: [],
        year: "2025",
        ranking: 2,
        timeline: 16,
        tier: "great",
        poster: "imgs/posters/apple tv/severance season 2.jpg",
        episodes: [
            {number: 1, title: "Hello, Ms. Cobel", tier: "great"},
            {number: 2, title: "Goodbye, Mrs. Selvig", tier: "best"},
            {number: 3, title: "Who Is Alive?", tier: "best"},
            {number: 4, title: "Woe's Hollow", tier: "great"},
            {number: 5, title: "Trojan's Horse", tier: "great"},
            {number: 6, title: "Attilla", tier: "great"},
            {number: 7, title: "Chikhai Bardo", tier: "brilliant"},
            {number: 8, title: "Sweet Vitriol", tier: "good"},
            {number: 9, title: "The After Hours", tier: "best"},
            {number: 10, title: "Cold Harbor", tier: "brilliant"},
        ]
    },
    {
        title: "Prime Target",
        type: "TV Show",
        saga: [],
        franchise: [],
        medium: [],
        year: "2025",
        ranking: 23,
        timeline: 17,
        tier: "innacuracy",
        poster: "imgs/posters/apple tv/prime target.jpg",
        episodes: [
            {number: 1, title: "A New Pattern", tier: "good"},
            {number: 2, title: "Syracuse", tier: "good"},
            {number: 3, title: "The Sequence", tier: "good"},
            {number: 4, title: "Kaplar", tier: "innacuracy"},
            {number: 5, title: "House of Wisdom", tier: "innacuracy"},
            {number: 6, title: "The Last Link", tier: "good"},
            {number: 7, title: "Prime Finder", tier: "innacuracy"},
            {number: 8, title: "The Key", tier: "innacuracy"},
        ]
    },
    {
        title: "F1",
        type: "Movie",
        saga: [],
        franchise: [],
        medium: [],
        year: "2025",
        ranking: 11,
        timeline: 18,
        tier: "best",
        poster: "imgs/posters/apple tv/f1.jpg"
    },
    {
        title: "Foundation [Season 3]",
        type: "TV Show",
        saga: [],
        franchise: ["Foundation"],
        medium: [],
        year: "2025",
        ranking: 17,
        timeline: 19,
        tier: "excellent",
        poster: "imgs/posters/apple tv/foundation season 3.jpg",
        episodes: [
            {number: 1, title: "A Song for the End of Everything", tier: "excellent"},
            {number: 2, title: "Shadows in the Math", tier: "excellent"},
            {number: 3, title: "When a Book Finds You", tier: "excellent"},
            {number: 4, title: "The Stress of Her Regard", tier: "excellent"},
            {number: 5, title: "Where Tyrants Spend Eternity", tier: "best"},
            {number: 6, title: "The Shape of Time", tier: "best"},
            {number: 7, title: "Foundaion's End", tier: "best"},
            {number: 8, title: "Skin in the Game", tier: "excellent"},
            {number: 9, title: "The Paths That Choose Us", tier: "excellent"},
            {number: 10, title: "The Darkness", tier: "great"},
        ]
    },
    {
        title: "Down Cemetery Road [Season 1]",
        type: "TV Show",
        saga: [],
        franchise: ["Down Cemetery Road"],
        medium: [],
        year: "2025",
        ranking: 20,
        timeline: 20,
        tier: "excellent",
        poster: "imgs/posters/apple tv/down cemetery road season 1.jpg",
        episodes: [
            {number: 1, title: "Almost True", tier: "excellent"},
            {number: 2, title: "A Kind of Grief", tier: "good"},
            {number: 3, title: "Filthy Work", tier: "good"},
            {number: 4, title: "My Friends Don't Like Me", tier: "good"},
            {number: 5, title: "Slow Dying", tier: "excellent"},
            {number: 6, title: "Neglected Waters", tier: "best"},
            {number: 7, title: "Lights Go Out", tier: "excellent"},
            {number: 8, title: "What Will Survive", tier: "excellent"},
        ]
    },
    {
        title: "Plur1bus [Season 1]",
        type: "TV Show",
        saga: [],
        franchise: ["Plur1bus"],
        medium: [],
        year: "2025",
        ranking: 14,
        timeline: 21,
        tier: "excellent",
        poster: "imgs/posters/apple tv/plur1bus season 1.jpg",
        episodes: [
            {number: 1, title: "We Is Us", tier: "great"},
            {number: 2, title: "Pirate Lady", tier: "excellent"},
            {number: 3, title: "Grenade", tier: "best"},
            {number: 4, title: "Please, Carol", tier: "excellent"},
            {number: 5, title: "Got Milk", tier: "excellent"},
            {number: 6, title: "HDP", tier: "best"},
            {number: 7, title: "The Gap", tier: "best"},
            {number: 8, title: "Charm Offensive", tier: "excellent"},
            {number: 9, title: "La Chica o El Mundo", tier: "best"},
        ]
    },
    {
        title: "Hijack [Season 2]",
        type: "TV Show",
        saga: [],
        franchise: ["Hijack"],
        medium: [],
        year: "2026",
        ranking: 15,
        timeline: 22,
        tier: "excellent",
        poster: "imgs/posters/apple tv/hijack season 2.jpg",
        episodes: [
            {number: 1, title: "Signal", tier: "excellent"},
            {number: 2, title: "Control", tier: "best"},
            {number: 3, title: "Baggage", tier: "excellent"},
            {number: 4, title: "Switch", tier: "best"},
            {number: 5, title: "Outage", tier: "best"},
            {number: 6, title: "Junction", tier: "best"},
            {number: 7, title: "Contact", tier: "excellent"},
            {number: 8, title: "Terminal", tier: "great"},

        ]
    },
    {
        title: "For All Mankind [Season 5]",
        type: "TV Show",
        saga: [],
        franchise: ["For All Mankind"],
        medium: [],
        year: "2026",
        ranking: 12,
        timeline: 23,
        tier: "best",
        poster: "imgs/posters/apple tv/for all mankind season 5.jpg",
        episodes: [
            {number: 1, title: "First Light", tier: "best"},
            {number: 2, title: "The Hard Six", tier: "best"},
            {number: 3, title: "Home", tier: "great"},
            {number: 4, title: "Open Source", tier: "excellent"},
            {number: 5, title: "Svoboda", tier: "best"},
            {number: 6, title: "No Sudden Moves", tier: "excellent"},
            {number: 7, title: "The Sirens of Titan", tier: "great"},
            {number: 8, title: "Brave New World", tier: "great"},
            {number: 9, title: "Sons and Daughters", tier: "excellent"},
            {number: 10, title: "This Land Is Our Land", tier: "brilliant"},
        ]
    },
    {
        title: "Star City [Season 1]",
        type: "TV Show",
        saga: [],
        franchise: ["For All Mankind"],
        medium: [],
        year: "2026",
        ranking: 7,
        timeline: 24,
        tier: "great",
        poster: "imgs/posters/apple tv/star city season 1.jpg",
        episodes: [
            {number: 1, title: "The Eyes", tier: "great"},
            {number: 2, title: "A Bear on a Chain", tier: "excellent"},
            {number: 3, title: "Bad Dancer", tier: "great"},
            {number: 4, title: "Dark Forest", tier: "excellent"},
            {number: 5, title: "Bite Your Elbow", tier: "best"},
            {number: 6, title: "Awl in a Sack", tier: "brilliant"},
            {number: 7, title: "Plow Deep", tier: "best"},
            {number: 8, title: "The Wolves", tier: "brilliant"},
        ]
    }
]