const entries = [
    {
        title: "Star Wars: Episode IV - A New Hope",
        type: "Movie",
        saga: ["Skywalker"],
        franchise: ["Original Trilogy"],
        medium: ["Live Action"],
        year: "1977",
        ranking: 7,
        timeline: 10,
        tier: "best",
        poster: "imgs/posters/star wars/episode 4 a new hope.jpg"
    },
    {
        title: "Star Wars: Episode V - The Empire Strikes Back",
        type: "Movie",
        saga: ["Skywalker"],
        franchise: ["Original Trilogy"],
        medium: ["Live Action"],
        year: "1980",
        ranking: 5,
        timeline: 11,
        tier: "great",
        poster: "imgs/posters/star wars/episode 5 the empire strikes back.jpg"
    },
    {
        title: "Star Wars: Episode VI - Return of the Jedi",
        type: "Movie",
        saga: ["Skywalker"],
        franchise: ["Original Trilogy"],
        medium: ["Live Action"],
        year: "1983",
        ranking: 6,
        timeline: 12,
        tier: "best",
        poster: "imgs/posters/star wars/episode 6 return of the jedi.jpg"
    },
    {
        title: "Star Wars: Episode I - The Phantom Menace",
        type: "Movie",
        saga: ["Skywalker"],
        franchise: ["Prequel Trilogy"],
        medium: ["Live Action"],
        year: "1999",
        ranking: 16,
        timeline: 2,
        tier: "good",
        poster: "imgs/posters/star wars/episode 1 the phantom menace.jpg"
    },
    {
        title: "Star Wars: Episode II - Attack of the Clones",
        type: "Movie",
        saga: ["Skywalker"],
        franchise: ["Prequel Trilogy"],
        medium: ["Live Action"],
        year: "2002",
        ranking: 11,
        timeline: 3,
        tier: "excellent",
        poster: "imgs/posters/star wars/episode 2 attack of the clones.jpg"
    },
    {
        title: "Star Wars: Episode III - Revenge of the Sith",
        type: "Movie",
        saga: ["Skywalker"],
        franchise: ["Prequel Trilogy"],
        medium: ["Live Action"],
        year: "2005",
        ranking: 3,
        timeline: 4,
        tier: "great",
        poster: "imgs/posters/star wars/episode 3 revenge of the sith.jpg"
    },
    {
        title: "Star Wars: Episode VII - The Force Awakens",
        type: "Movie",
        saga: ["Skywalker"],
        franchise: ["Sequel Trilogy"],
        medium: ["Live Action"],
        year: "2015",
        ranking: 12,
        timeline: 20,
        tier: "good",
        poster: "imgs/posters/star wars/episode 7 the force awakens.jpg"
    },
    {
        title: "Rogue One: A Star Wars Story",
        type: "Movie",
        saga: [],
        franchise: ["Andor"],
        medium: ["Live Action"],
        year: "2016",
        ranking: 1,
        timeline: 9,
        tier: "brilliant",
        poster: "imgs/posters/star wars/rogue one.jpg"
    },
    {
        title: "Star Wars: Episode VIII - The Last Jedi",
        type: "Movie",
        saga: ["Skywalker"],
        franchise: ["Sequel Trilogy"],
        medium: ["Live Action"],
        year: "2017",
        ranking: 8,
        timeline: 21,
        tier: "best",
        poster: "imgs/posters/star wars/episode 8 the last jedi.jpg"
    },
    {
        title: "Solo: A Star Wars Story",
        type: "Movie",
        saga: [],
        franchise: [],
        medium: ["Live Action"],
        year: "2018",
        ranking: 19,
        timeline: 5,
        tier: "innacuracy",
        poster: "imgs/posters/star wars/solo.jpg"
    },
    {
        title: "The Mandalorian [Season 1]",
        type: "TV Show",
        saga: ["Filoni-Verse"],
        franchise: ["The Mandalorian"],
        medium: ["Live Action"],
        year: "2019",
        ranking: 15,
        timeline: 13,
        tier: "good",
        poster: "imgs/posters/star wars/the mandalorian season 1.jpg",
        episodes: [
            {number: 1, title: "Chapter 1: The Mandalorian", tier: "excellent"},
            {number: 2, title: "Chapter 2: The Child", tier: "excellent"},
            {number: 3, title: "Chapter 3: The Sin", tier: "good"},
            {number: 4, title: "Chapter 4: Sanctuary", tier: "good"},
            {number: 5, title: "Chapter 5: The Gunslinger", tier: "good"},
            {number: 6, title: "Chapter 6: The Prisoner", tier: "excellent"},
            {number: 7, title: "Chapter 7: The Reckoning", tier: "excellent"},
            {number: 8, title: "Chapter 8: Redemption", tier: "excellent"}
        ]
    },
    {
        title: "The Mandalorian [Season 2]",
        type: "TV Show",
        saga: ["Filoni-Verse"],
        franchise: ["The Mandalorian"],
        medium: ["Live Action"],
        year: "2020",
        ranking: 9,
        timeline: 14,
        tier: "best",
        poster: "imgs/posters/star wars/the mandalorian season 2.jpg",
        episodes: [
            {number: 1, title: "Chapter 9: The Marshal", tier: "excellent"},
            {number: 2, title: "Chapter 10: The Passenger", tier: "excellent"},
            {number: 3, title: "Chapter 11: The Heiress", tier: "excellent"},
            {number: 4, title: "Chapter 12: The Seige", tier: "excellent"},
            {number: 5, title: "Chapter 13: The Jedi", tier: "best"},
            {number: 6, title: "Chapter 14: The Tragedy", tier: "best"},
            {number: 7, title: "Chapter 15: The Believer", tier: "great"},
            {number: 8, title: "Chapter 16: The Rescue", tier: "brilliant"}
        ]
    },
    {
        title: "The Book of Boba Fett",
        type: "TV Show",
        saga: ["Filoni-Verse"],
        franchise: ["The Mandalorian"],
        medium: ["Live Action"],
        year: "2021",
        ranking: 18,
        timeline: 15,
        tier: "innacuracy",
        poster: "imgs/posters/star wars/the book of boba fett.jpg",
        episodes: [
            {number: 1, title: "Chapter 1: Stranger in a Strange Land", tier: "innacuracy"},
            {number: 2, title: "Chapter 2: The Tribes of Tatooine", tier: "innacuracy"},
            {number: 3, title: "Chapter 3: The Streets of Mos Espa", tier: "mistake"},
            {number: 4, title: "Chapter 4: The Gathering Storm", tier: "innacuracy"},
            {number: 5, title: "Chapter 5: Return of the Mandalorian", tier: "excellent"},
            {number: 6, title: "Chapter 6: From the Desert Comes a Stranger", tier: "excellent"},
            {number: 7, title: "Chapter 7: In the Name of Honor", tier: "good"}
        ]
    },
    {
        title: "Obi-Wan Kenobi",
        type: "TV Show",
        saga: [],
        franchise: [],
        medium: ["Live Action"],
        year: "2022",
        ranking: 10,
        timeline: 6,
        tier: "excellent",
        poster: "imgs/posters/star wars/obi wan kenobi.jpg",
        episodes: [
            {number: 1, title: "Part I", tier: "good"},
            {number: 2, title: "Part II", tier: "excellent"},
            {number: 3, title: "Part III", tier: "best"},
            {number: 4, title: "Part IV", tier: "excellent"},
            {number: 5, title: "Part V", tier: "excellent"},
            {number: 6, title: "Part VI", tier: "great"}
        ]
    },
    {
        title: "Andor [Season 1]",
        type: "TV Show",
        saga: [],
        franchise: ["Andor"],
        medium: ["Live Action"],
        year: "2022",
        ranking: 4,
        timeline: 7,
        tier: "great",
        poster: "imgs/posters/star wars/andor season 1.jpg",
        episodes: [
            {number: 1, title: "Kassa", tier: "excellent"},
            {number: 2, title: "That Would Be Me", tier: "excellent"},
            {number: 3, title: "Reckoning", tier: "best"},
            {number: 4, title: "Aldhani", tier: "excellent"},
            {number: 5, title: "The Axe Forgets", tier: "excellent"},
            {number: 6, title: "The Eye", tier: "brilliant"},
            {number: 7, title: "Announcement", tier: "best"},
            {number: 8, title: "Narkina 5", tier: "best"},
            {number: 9, title: "Nobody's Listening!", tier: "great"},
            {number: 10, title: "One Way Out", tier: "brilliant"},
            {number: 11, title: "Daughter of Ferrix", tier: "great"},
            {number: 12, title: "Rix Road", tier: "great"},
        ]
    },
    {
        title: "The Mandalorian [Season 3]",
        type: "TV Show",
        saga: ["Filoni-Verse"],
        franchise: ["The Mandalorian"],
        medium: ["Live Action"],
        year: "2023",
        ranking: 17,
        timeline: 16,
        tier: "innacuracy",
        poster: "imgs/posters/star wars/the mandalorian season 3.jpg",
        episodes: [
            {number: 1, title: "Chapter 17: The Apostate", tier: "good"},
            {number: 2, title: "Chapter 18: The Mines of Mandalore", tier: "good"},
            {number: 3, title: "Chapter 19: The Convert", tier: "innacuracy"},
            {number: 4, title: "Chapter 20: The Foundling", tier: "good"},
            {number: 5, title: "Chapter 21: The Pirate", tier: "excellent"},
            {number: 6, title: "Chapter 22: Guns for Hire", tier: "mistake"},
            {number: 7, title: "Chapter 23: The Spies", tier: "good"},
            {number: 8, title: "Chapter 24: The Return", tier: "excellent"}
        ]
    },
    {
        title: "Ahsoka [Season 1]",
        type: "TV Show",
        saga: ["Filoni-Verse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2023",
        ranking: 14,
        timeline: 17,
        tier: "good",
        poster: "imgs/posters/star wars/ahsoka season 1.jpg",
        episodes: [
            {number: 1, title: "Part One: Master and Apprentice", tier: "good"},
            {number: 2, title: "Part Two: Toil and Trouble", tier: "good"},
            {number: 3, title: "Part Three: Time to Fly", tier: "good"},
            {number: 4, title: "Part Four: Fallen Jedi", tier: "excellent"},
            {number: 5, title: "Part Five: Shadow Warrior", tier: "best"},
            {number: 6, title: "Part Six: Far, Far Away", tier: "excellent"},
            {number: 7, title: "Part Seven: Dreams and Madness", tier: "good"},
            {number: 8, title: "Part Eight: The Jedi, the Witch and the Warlord", tier: "excellent"},
        ]
    },
    {
        title: "The Acolyte",
        type: "TV Show",
        saga: [],
        franchise: [],
        medium: ["Live Action"],
        year: "2024",
        ranking: 21,
        timeline: 1,
        tier: "mistake",
        poster: "imgs/posters/star wars/the acolyte.jpg",
        episodes: [
            {number: 1, title: "Lost / Found", tier: "innacuracy"},
            {number: 2, title: "Revenge / Justice", tier: "innacuracy"},
            {number: 3, title: "Destiny", tier: "blunder"},
            {number: 4, title: "Day", tier: "innacuracy"},
            {number: 5, title: "Night", tier: "excellent"},
            {number: 6, title: "Teach / Corrupt", tier: "innacuracy"},
            {number: 7, title: "Choice", tier: "mistake"},
            {number: 8, title: "The Acolyte", tier: "innacuracy"}
        ]
    },
    {
        title: "Skleteton Crew",
        type: "TV Show",
        saga: ["Filoni-Verse"],
        franchise: [],
        medium: ["Live Action"],
        year: "2024",
        ranking: 20,
        timeline: 18,
        tier: "innacuracy",
        poster: "imgs/posters/star wars/skeleton crew.jpg",
        episodes: [
            {number: 1, title: "This Could Be A Real Adventure", tier: "innacuracy"},
            {number: 2, title: "Way, Way Out Past The Barrier", tier: "innacuracy"},
            {number: 3, title: "Very Interesting, As An Astrogation Problem", tier: "innacuracy"},
            {number: 4, title: "Can't Say I Remember No At Attin", tier: "innacuracy"},
            {number: 5, title: "You Have A Lot To Learn About Pirates", tier: "innacuracy"},
            {number: 6, title: "Zero Friends Again", tier: "innacuracy"},
            {number: 7, title: "We're Gonna Be In So Much Trouble", tier: "innacuracy"},
            {number: 8, title: "The Real Good Guys", tier: "innacuracy"}
        ]
    },
    {
        title: "Andor [Season 2]",
        type: "TV Show",
        saga: [],
        franchise: ["Andor"],
        medium: ["Live Action"],
        year: "2025",
        ranking: 2,
        timeline: 8,
        tier: "brilliant",
        poster: "imgs/posters/star wars/andor season 2.jpg",
        episodes: [
            {number: 1, title: "One Year Later", tier: "best"},
            {number: 2, title: "Sagrona Teema", tier: "excellent"},
            {number: 3, title: "Harvest", tier: "great"},
            {number: 4, title: "Ever Been to Ghorman?", tier: "excellent"},
            {number: 5, title: "I Have Friends Everywhere", tier: "best"},
            {number: 6, title: "What a Festive Evening", tier: "great"},
            {number: 7, title: "Messenger", tier: "great"},
            {number: 8, title: "Who Are You?", tier: "brilliant"},
            {number: 9, title: "Welcome to the Rebellion", tier: "brilliant"},
            {number: 10, title: "Make It Stop", tier: "brilliant"},
            {number: 11, title: "Who Else Knows?", tier: "brilliant"},
            {number: 12, title: "Jedha, Kyber, Erso", tier: "great"},
        ]
    },
    {
        title: "The Mandalorian and Grogu",
        type: "Movie",
        saga: ["Filoni-Verse"],
        franchise: ["The Mandalorian"],
        medium: ["Live Action"],
        year: "2026",
        ranking: 13,
        timeline: 19,
        tier: "good",
        poster: "imgs/posters/star wars/the mandalorian and grogu.jpg"
    }
]